const
    // See https://www.redblobgames.com/grids/hexagons for these numbers.
    HEXAGON_HEIGHT_RATIO = 2 / Math.sqrt(3),
    HORIZONTAL_HEIGHT_MULTIPLIER = 2,
    VERTICAL_HEIGHT_MULTIPLIER = 3.5,

    // Pixel height for bottom perspective. Specific to the svgs.
    HEIGHT_BOTTOM_PIXELS = 15,

    // Svg hexagon base width is 100px. Calculate height in pixels.
    HORIZONTAL_HEIGHT_HEXAGONS_PIXELS =
        100 * HEXAGON_HEIGHT_RATIO * HORIZONTAL_HEIGHT_MULTIPLIER,
    VERTICAL_HEIGHT_HEXAGONS_PIXELS =
        100 * HEXAGON_HEIGHT_RATIO * VERTICAL_HEIGHT_MULTIPLIER,

    // Percentage of total height occupied by hexagons.
    HORIZONTAL_HEIGHT_RATIO =
        HORIZONTAL_HEIGHT_HEXAGONS_PIXELS /
        (HORIZONTAL_HEIGHT_HEXAGONS_PIXELS + HEIGHT_BOTTOM_PIXELS),
    VERTICAL_HEIGHT_RATIO =
        VERTICAL_HEIGHT_HEXAGONS_PIXELS /
        (VERTICAL_HEIGHT_HEXAGONS_PIXELS + HEIGHT_BOTTOM_PIXELS)

export const HORIZONTAL_HEXAGON_WIDTH_UNIT_RATIO = 1 / 4
export const VERTICAL_HEXAGON_WIDTH_UNIT_RATIO = 1 / 3
export const HORIZONTAL_HEXAGON_HEIGHT_UNIT_RATIO =
    HORIZONTAL_HEIGHT_RATIO / HORIZONTAL_HEIGHT_MULTIPLIER
export const VERTICAL_HEXAGON_HEIGHT_UNIT_RATIO =
    VERTICAL_HEIGHT_RATIO / VERTICAL_HEIGHT_MULTIPLIER
